import { StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Roboto",
    fontSize: 8,
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 30,
    color: "#333",
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  companyDetails: {
    flexDirection: "column",
  },
  companyName: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 1,
  },
  companyAddress: {
    fontSize: 9,
    lineHeight: 1.3,
  },
  invoiceInfoContainer: {
    flexDirection: "column",
    alignItems: "flex-end",
    marginTop: 5,
  },
  invoiceTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 6,
  },
  invoiceDetails: {
    flexDirection: "row",
    marginBottom: 1,
    fontSize: 9,
  },
  invoiceLabel: {
    width: 45,
    textAlign: "right",
    marginRight: 5,
  },
  invoiceValue: {
    width: 110,
    textAlign: "left",
    fontWeight: "bold",
  },
  section: {
    marginBottom: 10,
  },
  addressColumnsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  addressColumn: {
    width: "50%",
  },
  addressBlock: {
    borderWidth: 1,
    borderColor: "#000",
    padding: 5,
  },
  importerBlock: {},
  addressPadding: {
    height: 7,
  },
  shippingPairBlock: {
    borderWidth: 1,
    borderColor: "#000",
    flexDirection: "row",
    flex: 1,
  },
  shippingPairItem: {
    width: "50%",
    padding: 3.5,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    flex: 1,
  },
  shippingPairItemLeft: {
    width: "50%",
    padding: 3.5,
    borderRightWidth: 1,
    flex: 1,
    borderRightColor: "#000",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  shippinPairBelow: {
    width: '25%',
    padding: 1,
    justifyContent: 'flex-start',
    flex: 1,
  },
  shippingBlockValue: {
    fontSize: 8,
    lineHeight: 1.2,
    wordBreak: 'break-word',
  },
  shippingLabelStyle: {
    width: 150,
    height: 20,
    lineHeight: 1.3,
  },
  addressBlockTitle: {
    fontWeight: "bold",
    marginBottom: 3,
    fontSize: 8,
  },
  addressRow: {
    flexDirection: "row",
    marginBottom: 1,
  },
  addressLabel: {
    minWidth: 45,
  },
  shippingLabelStyleWidth: {
    width: 150,
    height: 20,
    lineHeight: 1.3,
  },
  addressColon: {
    width: 10,
    textAlign: "center",
  },
  addressValue: {
    flex: 1,
  },
  importantNotice: {
    padding: 8,
    textAlign: "center",
    marginBottom: 15,
    fontSize: 10,
    fontWeight: "bold",
    border: '2px solid red',
  },
  importantNumber: {
    fontSize: 12,
    fontWeight: "bold",
  },
  bankInfoContainer: {
    borderWidth: 1,
    borderColor: "#000",
    marginBottom: 15,
  },
  bankHeader: {
    padding: 3,
    fontWeight: "bold",
    fontSize: 9,
    backgroundColor: "#e8f0ff",
    color: "#0b5ed7",
    borderBottomWidth: 1,
    borderBottomColor: "#000",
  },
  bankRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#000",
  },
  bankRowLast: {
    flexDirection: "row",
  },
  bankCellLabel: {
    width: "25%",
    padding: 3,
    borderRightWidth: 1,
    borderRightColor: "#000",
    fontWeight: "bold",
    backgroundColor: "#f2f2f2",
  },
  bankCellValuePair: {
    width: "35%",
    padding: 3,
    borderRightWidth: 1,
    borderRightColor: "#000",
  },
  bankCellValueWide: {
    width: "75%",
    padding: 3,
  },
  bankCellLabelPair: {
    width: "20%",
    padding: 3,
    borderRightWidth: 1,
    borderRightColor: "#000",
    fontWeight: "bold",
    backgroundColor: "#f2f2f2",
  },
  bankCellValuePairLast: {
    width: "35%",
    padding: 3,
  },
  bankCellHiddenText: {
    color: "transparent",
    borderRightWidth: 0,
  },
  noteAndAmountContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 15,
    marginTop: 6,
  },
  noteContainer: {
    border: '2px solid red',
    padding: 8,
    width: "55%",
  },
  noteText: {
    marginBottom: 2,
    fontSize: 7,
    lineHeight: 1.3,
  },
  noteTitle: {
    fontWeight: "bold",
    fontSize: 8,
    marginBottom: 4,
  },
  amountAndConfirmationContainer: {
    width: "40%",
    flexDirection: "column",
    alignItems: "flex-end",
  },
  amountBox: {
    flexDirection: "column",
    alignItems: "flex-end",
    marginBottom: 5,
  },
  amountLabel: {
    fontSize: 9,
    marginBottom: 2,
  },
  amountValueBox: {
    borderWidth: 1,
    borderColor: "#000",
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 3,
  },
  amountValue: {
    fontSize: 12,
    fontWeight: "bold",
  },
  bankChargeText: {
    fontSize: 7,
    color: "red",
    textAlign: "right",
  },
  confirmationSection: {
    flexDirection: "column",
    alignItems: "center",
    marginTop: 5,
    width: "90%",
    alignSelf: "center",
  },
  confirmationText: {
    fontSize: 7,
    marginBottom: 10,
    textAlign: "center",
  },
  signatureArea: {
    borderTopWidth: 0.5,
    borderTopColor: "#555",
    width: 150,
    paddingTop: 2,
    marginTop: 5,
    textAlign: "center",
  },
  table: {
    width: "100%",
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#000",
    marginBottom: 5,
  },
  tableRow: {
    flexDirection: "row",
    minHeight: 25,
  },
  tableHeader: {
    backgroundColor: "#e8f0ff",
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    alignItems: "center",
  },
  tableColHeader: {
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#000",
    borderLeftWidth: 0,
    borderTopWidth: 0,
    paddingVertical: 3,
    paddingHorizontal: 2,
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 7,
    color: "#0b5ed7",
    height: "100%",
    display: "flex",
    justifyContent: "center",
  },
  tableCol: {
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#000",
    borderLeftWidth: 0,
    borderTopWidth: 0,
    padding: 3,
    fontSize: 8,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  colNo: { width: "5%", textAlign: "center" },
  colRef: { width: "12%" },
  colMaker: { width: "18%" },
  colDesc: { width: "30%" },
  colUnit: { width: "10%", textAlign: "right" },
  colFreight: { width: "10%", textAlign: "right" },
  colAmount: { width: "10%", textAlign: "right" },
  footerTotals: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#000",
    paddingTop: 4,
    justifyContent: "space-between",
    fontSize: 9,
    alignItems: "center",
  },
  footerLeft: {
    flexDirection: "row",
    width: "30%",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerRight: {
    flexDirection: "row",
    width: "55%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  totalLabel: { fontWeight: "bold" },
  totalValue: { fontWeight: "bold", textAlign: "right", minWidth: 50 },
  footerItem: { fontWeight: "bold", marginHorizontal: 15 },
  invoiceTitle: {
    textAlign: "center",
    fontSize: "15px",
    fontWeight: "bold",
    color: "#0b5ed7",
    marginTop: 5,
    marginBottom: 10,
  },
  shippingBlockTitle: { fontWeight: "bold", fontSize: 8, lineHeight: 1.3 },
  shippingBlockContainer: { flexDirection: 'column', padding: 3, margin: 0 },
  signatureContainer: { display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  signature: { width: "100px", position: "relative", left: "25%" },
  stamp: { width: "50px" },
  contactInfoText: { fontSize: 7, textAlign: 'center', marginBottom: 2 },
  invoiceSignatureText: { fontSize: 7, textAlign: 'center', marginBottom: 1, width: "100%" },
  importantNoticeHeader: { color: 'red' },
  invoiceFooter: { display: "flex", flexDirection: "column", justifyContent: "flex-end" },
  signatureContainerAlt: { display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  signatureAlt: { width: "100px", position: "relative", left: "25%" },
  stampAlt: { width: "50px" },
  containerBlock: { borderWidth: 1, borderColor: "#000", padding: 10, width: "80%", marginVertical: 15, alignSelf: "center" },
  containerBlockTitle: { fontWeight: "bold", fontSize: 10, marginBottom: 5, textAlign: "center" },
  wideLabel: { width: 90 },
});

export default styles;
